quizXZ/models.py
"""models.py for the quiz system."""
from django.conf import settings
from django.db import models


class Quiz(models.Model):
    """Quiz model."""

    users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, through="QuizUser", blank=True)
    name = models.CharField(max_length=20, default="")
    diffLevels = (
        (0, "easy"),
        (1, "medium"),
        (2, "hard"),
    )
    subject = models.CharField(max_length=200, default="", blank=True)
    difficulty = models.IntegerField(choices=diffLevels, default=0, blank=True)

    def __str__(self):
        """To string method for the quiz model."""
        return self.name


class Question(models.Model):
    """Question model."""

    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    text = models.CharField(max_length=500, default="")

    def __str__(self):
        """To string method for the question model."""
        return self.text


class Choice(models.Model):
    """Choice model."""

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)
    text = models.CharField(max_length=300, default="")
    pointTypes = (
        (0, 0),
        (1, 0.5),
        (2, 1)
    )
    point = models.IntegerField(choices=pointTypes, default=0)

    def __str__(self):
        """To string method for the choice model."""
        return self.text


class QuizUser(models.Model):
    """QuizUser model that specifies the ManyToMany relatinoship between Django User model and the Quiz model."""

    quiz = models.ForeignKey(Quiz)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)

    class Meta:
        """Set the combined foreign keys to be unique."""

        unique_together = ('user', 'quiz')

quizXZ/templates/base.html
<!DOCTYPE html>
<!-- base.html -->
<html>
  <head>
    <base href = "http://xzhang.master.cs.haverford.edu" />
    <title>{{title}}</title>
    <link href = "/static/styles.css" rel = "stylesheet" type = "text/css" />
    <script>
      {% block script %}{% endblock %}
    </script>
  </head>
  <body>
    {% block nav %}{% endblock %}
    {% block content %}{% endblock %}
  </body>
</html>

quizXZ/templates/choiceList.html
{% extends "nav2.html" %}

{% block content %}
	<form action="/{{quizID}}/{{questionID}}/delete_choice/" method="post">{% csrf_token %}
	  <fieldset>
	    <legend> Existing Choices </legend>
		  <ol>
		  {% for list in lists %}
		      	{% if questionID == list.question.id %}
		      		<li>
				{{ list.text }}
				<button type="hidden" name="delete" class="button" value="{{ list.id }}">Delete this choice</button>
				</li>
				<br>
		      	{% endif %}
		  {% endfor %}
		  </ol>
		</fieldset>
	</form>

	<div id="button">
	<a href="/{{quizID}}/{{questionID}}/create_choice/" class="button">Back To Create Choices</a>
	</div>
{% endblock %}

quizXZ/templates/createQuestion.html
{% extends "nav2.html" %}

{% block content %}
	<h1><strong>Create a Question</strong></h1>
	<form action="/{{quizID}}/add_question/" method="post">{% csrf_token %}
		<fieldset>
		  <legend>Create A New Question for "{{quiz_name}}"</legend>
		  {{ form.as_ul }}
		  <input type="submit" class="button" value="Save this Question">
		</fieldset>
	</form>

	<form action="/{{quizID}}/question_list/" method="get">{% csrf_token %}

		<fieldset>
		  <legend> Existing Questions </legend>

		<ol>
		  {% for list in lists %}
			{% if quizID == list.quiz.id %}
				<li>
				    <a href = "/{{quizID}}/{{list.id}}/create_choice/">{{ list.text }}</a>
				</li>
		      	{% endif %}
		  {% endfor %}
		  </ol>
		<input type="submit" class="button" value="Delete Questions">
		</fieldset>
	</form>

	<div id="button">
	<a href = "/create_quiz/" class="button">Back To Create Quizzes</a>
	</div>
{% endblock %}

quizXZ/templates/createQuiz.html
{% extends "nav2.html" %}

{% block content %}
	<h1><strong>Create a Quiz</strong></h1>
	<form action="/add_quiz/" method="post">{% csrf_token %}
		<fieldset>
			<legend>Create A New Quiz</legend>
			{{ form.as_ul }}
			<input type="submit" class="button" value="Save this quiz">
		</fieldset>
	</form>
	
	<form action="/quiz_list/" method="get">{% csrf_token %}

		<fieldset>
		  <legend> Existing quizzes </legend>

		<ol>
		  {% for list in lists %}
			<li>
			   <a href = "/{{list.id}}/create_question/">{{ list.name }}</a>
			</li>
		  {% endfor %}
		</ol>
		<input type="submit" class="button" value="Delete Quizzes">
		</fieldset>
	</form>
{% endblock %}

quizXZ/templates/homepage.html
{% extends "nav2.html" %}

{% block content %}
	<h1><strong>Hello {{name}}!</strong></h1>
	<h1> Welcome to the Quiz System </h1>

	{% if request.user.is_superuser %}
    <div id="button">
		<a href="/create_quiz/" class="button">Create Your Quizzes</a>
		<a href="/users/report/" class="button">Check Users Quiz Reports</a>
	</div>
	{% endif %}

	<div id="button">
		<a href="/my/report/" class="button">Check Your Quiz Reports</a>
		<a href="/quizzes/" class="button">Proceed To Your Quizzes</a>
    </div>
{% endblock %}

quizXZ/templates/main.html
{% extends "nav1.html" %}
{% block content %}
<h1><strong>Welcome to the Quiz System</strong></h1>
{% endblock %}

quizXZ/templates/nav1.html
{% extends "base.html" %}

{% block nav %}
<nav>
	<ul>
  		<li><a href="/login">Login</a></li>
  		<li><a href="/signup">Signup</a></li>
  	</ul>
</nav>
{% endblock %}

quizXZ/templates/nav2.html
{% extends "base.html" %}

{% block nav %}
<nav>
	<ul>
		<li><a>Welcome {{user.username}}:</a></li>
  		<li><a href="/my"> Home</a></li>
		<li><a href="/submitLogout">Logout</a></li>
	</ul>
</nav>
{% endblock %}

quizXZ/templates/questions.html
{% extends "nav2.html" %}

{% block content %}
	<h1><strong>Please answer the following questions to your best: Best Of Luck!</strong></h1>
	<form action="/{{quiz.id}}/save_userchoice/" method="post"> {% csrf_token %}
	<fieldset>
	    {{error}}
		<legend>Below are your quiz questions</legend>
		{% for question in quiz.question_set.all %}
		<p><label>{{question.text}}</label></p>
		{% for choice in question.choice_set.all %}
		&nbsp;&nbsp;<input type="checkbox" name="userchoice" id="choice" value="{{choice.id}}"></input>
		<label class="radioandcheckbox">{{choice.text}}</label>
		<br>
		{% endfor %}
		<br>
		{% endfor %}
	</fieldset>
	<br>
	<input type="submit" id="Submit" class="button" name="Submit" value = "Submit">
	</form>
{% endblock %}

quizXZ/templates/quizList.html
{% extends "nav2.html" %}

{% block content %}
	<form action="/delete_quiz/" method="post">{% csrf_token %}
	  <fieldset>
	    <legend> Existing Quizzes </legend>
		  <ol>
		  {% for list in lists %}
			<li>
			{{ list.name }}
			<button type="hidden" name="delete" class="button" value="{{ list.id }}">Delete this quiz</button>
			</li>
		  {% endfor %}
		  </ol>
		</fieldset>
	</form>

	<div id="button">
	<a href="/create_quiz/" class="button">Back To Create Quizzes</button>
	</a>
	</div>
{% endblock %}

quizXZ/templates/quizzes.html
{% extends "nav2.html" %}

{% block content %}
	<div id="quizzes">
	  <h1> Lists of Quizzes you haven't taken </h1>
	  <p>Click on the quiz whenever you are ready! Note that the quiz is timed and can be only taken once.</p>
	  <ol>
	  {% for quiz in quizzes %}
	    <li>
		<a href="{{quiz.id}}/questions/">{{ quiz.name }}</a>
	    </li>
	  {% endfor %}
	  </ol>
	</div>
{% endblock %}

quizXZ/templates/report.html
{% extends "nav2.html" %}

{% block content %}
	<div id=wraparound>
		<h1>Below are the quiz results for {{user_name}}:</h1>
		<br>
		<h1 id=highlight>{{user_name}} got {{score}} out of {{total}} in {{quiz_name}}.</h1>
	</div>
	<div id="button">
		<a href="/quizzes/" class="button">Back To Quizzes</a>
		{% if request.user.is_superuser %}
		<a href="/users/report/" class="button">Back To Reports</a>
		{% else %}
		<a href="/my/report/" class="button">Back To Reports</a>
		{% endif %}
	</div>
{% endblock %}

quizXZ/templates/signup.html
{% extends "nav1.html" %}

{% block content %}
<h1><strong>Welcome to the Quiz System</strong></h1>
<form action="/submitSignup/" method="post">{% csrf_token %}
  {{error}}
  <fieldset>
    <legend>Please sign up</legend>
    <p>Create your account below</p>
    <ul>
      {{ form.as_ul}}
    </ul>
    <div id="button">
    	<input type="submit" id="signup" name="signup" class="button" value = "Sign up">
    </div>
  </fieldset>
</form>
<br>
{% endblock %}